### ISSUE TITLE
Improve menu bar interaction on mobile 

### ISSUE THREAD

**Issue by perriefidelis** [oscafrica/oscafrica.org-v2#21]
See [prototype](https://www.figma.com/proto/dDQ0f43gracsqn1LJYk91E/New-OSCA-website?node-id=2701%3A0&scaling=min-zoom&page-id=1087%3A0) for how the menu bar interaction should work.

Check out the [Figma file ](https://www.figma.com/file/dDQ0f43gracsqn1LJYk91E/New-OSCA-website?node-id=2701%3A0)

**Comment by alabobriggs** [comment]
@Scentjuls let me know if you need help getting this done.

**Comment by alabobriggs** [comment]
@Scentjuls how is this coming up?

**Comment by Scentjuls** [comment]
> @Scentjuls how is this coming up?

Its going on well, i should have a PR up today.

**Comment by alabobriggs** [comment]
Hello @Scentjuls have you been able to make any progress on this?
