### ISSUE TITLE
Fix image sizes on mobile version 

### ISSUE THREAD

**Issue by perriefidelis** [oscafrica/oscafrica.org-v2#25]

**Comment by alabobriggs** [comment]
No description

**Comment by alabobriggs** [comment]
Please provide description

**Comment by alabobriggs** [comment]
@perriefidelis please provide description for this

**Comment by alabobriggs** [comment]
@Anita-ihuman are you available to take on this?

**Comment by Anita-ihuman** [comment]
Yes I am, will get to it.

**Comment by Anita-ihuman** [comment]
@perriefidelis You did not specify which images this issue is meant to fix. Can you provide more details, please?

**Comment by Anita-ihuman** [comment]
@perriefidelis @alabobriggs I believe these repositories could use an issue template. I will be helpful in creating new issues.

**Comment by perriefidelis** [comment]
All the images on the mobile version are zoomed/cropped. 

I had initially requested a call with @alabobriggs to show him what I mean, while I use the inspect feature on chrome but the call never happened. 
The goal of this issue is to make sure images on mobile are not cropped but follows how it is on the mock-ups. 

If you’re up for a call, we can do that later today. Drop your calendar availability or give me a time.

**Comment by alabobriggs** [comment]
> All the images on the mobile version are zoomed/cropped.
> 
> I had initially requested a call with @alabobriggs to show him what I mean, while I use the inspect feature on chrome but the call never happened.
> The goal of this issue is to make sure images on mobile are not cropped but follows how it is on the mock-ups.
> 
> If you’re up for a call, we can do that later today. Drop your calendar availability or give me a time.

can't find this issue on mobile. Please let us schedule a meeting on this. We can handle this asynchronously using [loom](loom.com)

**Comment by perriefidelis** [comment]
For context; See screenshots: 

![3CFAB55A-EF50-4466-8232-203967DA6851](https://user-images.githubusercontent.com/30669761/126218365-317689a3-698b-46c9-941b-34f661cfb886.png)
![F0D8D025-C739-44A2-A3A5-1B1A2624FAB1](https://user-images.githubusercontent.com/30669761/126218396-14c025f4-a006-4bbb-9a54-d83e18bae217.png)
![0E0EE68F-CC48-4F66-A30E-C935BF6604D5](https://user-images.githubusercontent.com/30669761/126218316-07f3ba7d-a141-4f47-bcc0-751d9c7c67cc.png)
