### ISSUE TITLE
Add Google Analytics Tracking Info

### ISSUE THREAD

**Issue by BolajiAyodeji** [oscafrica/oscafrica.org-v2#28]
Add gtag.js tracking info to the website

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-77563678-4"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-77563678-4');
</script>
```

**Comment by BolajiAyodeji** [comment]
Is there any possibility of getting this up today, please? We're losing traffic counts already, @alabobriggs, my chief.

**Comment by alabobriggs** [comment]
Yes we can, approving now

**Comment by alabobriggs** [comment]
> Is there any possibility of getting this up today, please? We're losing traffic counts already, @alabobriggs, my chief.

@BolajiAyodeji I should be able to but that will be late tonight. I will be AFK today

**Comment by BolajiAyodeji** [comment]
> > Is there any possibility of getting this up today, please? We're losing traffic counts already, @alabobriggs, my chief.
> 
> @BolajiAyodeji I should be able to but that will be late tonight. I will be AFK today

Okay boss!

**Comment by alabobriggs** [comment]
@BolajiAyodeji added script for this, please provide new google Analytics dashboard. Left a request to add me to the dashboard.

**Comment by alabobriggs** [comment]
@BolajiAyodeji reminder for the google analytics stream id

**Comment by BolajiAyodeji** [comment]
@alabobriggs I just shared some feedback on this. I think we should proceed with the tracking code I shared earlier.

**Comment by alabobriggs** [comment]
> @alabobriggs I just shared some feedback on this. I think we should proceed with the tracking code I shared earlier.

Got it, I just made the necessary updates. Please confirm on the GA dashboard.

**Comment by BolajiAyodeji** [comment]
It doesn't work yet, chief. Can you check again and possibly point me to the commit that implements this?

**Comment by BolajiAyodeji** [comment]
@alabobriggs any update on this boss?

**Comment by alabobriggs** [comment]
Yes. I updated the code to the existing GA ID

**Comment by alabobriggs** [comment]
I don't have access to the dashboard so I can't test properly

**Comment by BolajiAyodeji** [comment]
Alright! But you do have access. I thought you requested for access and @samswag granted you?
