### ISSUE TITLE
Add Discord Widget

### ISSUE THREAD

**Issue by BolajiAyodeji** [oscafrica/oscafrica.org-v2#32]
Add Discord members iframe somewhere on the /community page. Demo: https://codepen.io/iambolajiayo/pen/abJawzB

```
<iframe src="https://discord.com/widget?id=676252299093475348" width="350" height="500" allowtransparency="true" frameborder="0" sandbox="allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts"></iframe>
```

**Comment by BolajiAyodeji** [comment]
@perriefidelis can we get a sample design for this, please?

**Comment by alabobriggs** [comment]
@mrstevea are you available to make a design for this?

**Comment by mrstevea** [comment]
Taking a look @alabobriggs

**Comment by alabobriggs** [comment]
@mrstevea Have you you been to make any progress on this?

**Comment by mrstevea** [comment]
None yet @alabobriggs. Getting on a call with @perriefidelis later tonight, will discuss that with her.

**Comment by perriefidelis** [comment]
@mrstevea

What we're trying to achieve with this issues is add a [discord widget](https://codepen.io/iambolajiayo/pen/abJawzB) in the community page. 

Let's talk about it over our meeting today, now that I've gotten more clarification from @BolajiAyodeji
