### ISSUE TITLE
Update Bolaji Ayodeji's headshot

### ISSUE THREAD

**Issue by BolajiAyodeji** [oscafrica/oscafrica.org-v2#35]
Update headshot for Bolaji Ayodeji in /team page to [this](https://res.cloudinary.com/bolaji/image/upload/v1644047224/headshot-full.jpg)

**Comment by saintmalik** [comment]
Hello guys? Mind picking this issue up? @alabobriggs

**Comment by alabobriggs** [comment]
Hello @saintmalik, the image provided needs some work before we can replace the current image. I will assign this issue to you once that is done.

**Comment by saintmalik** [comment]
> Hello @saintmalik, the image provided needs some work before we can replace the current image. I will assign this issue to you once that is done.

Okay thanks 😊

**Comment by BolajiAyodeji** [comment]
@oscafrica/design && @perriefidelis, any hope on an ETA for this, please?

**Comment by perriefidelis** [comment]
Sorry for the delay on this, here;

- [Inactive](https://www.figma.com/file/dDQ0f43gracsqn1LJYk91E/New-OSCA-website?node-id=4352%3A8446&t=GUyH8bCNREq1qFDq-4)
- [Active](https://www.figma.com/file/dDQ0f43gracsqn1LJYk91E/New-OSCA-website?node-id=4352%3A8445&t=GUyH8bCNREq1qFDq-4)

**Comment by perriefidelis** [comment]
@BolajiAyodeji here;

- [Active](https://www.figma.com/file/dDQ0f43gracsqn1LJYk91E/New-OSCA-website?node-id=4363%3A8473&t=GUyH8bCNREq1qFDq-4) 
- [Inactive](https://www.figma.com/file/dDQ0f43gracsqn1LJYk91E/New-OSCA-website?node-id=4363%3A8474&t=GUyH8bCNREq1qFDq-4)
