### ISSUE TITLE
Twitter account banned - probably best to remove

### ISSUE THREAD

**Issue by ioana-chiorean** [oscafrica/oscafrica.org-v2#76]
Hey 
both on the main page and also conference page the Twitter account linked in https://twitter.com/oscafrica which seems to be suspended.

Not sure what is your plan with it - probably recovering it - but I think would be safe to remove it and people might be put off by this.  Or update if you have a new account.

**Comment by BolajiAyodeji** [comment]
Thanks for this issue, @ioana-chiorean. We tried recovering the suspended account but we're yet to make progress with that we have a new conference Twitter account which has been added now. Cheers!

**Comment by BolajiAyodeji** [comment]
@all-contributors please add @ioana-chiorean for ideas.
